### ISSUE TITLE
database

### ISSUE THREAD

**Issue by JaimeRax** [PetCare-Veterinay/PetCare#1]
### **table structure for database**

Creación de la base de datos normalizada, modelo Entidad Relación.

[ER_PetCare.txt](https://github.com/PetCare-Veterinay/PetCare/files/12799358/ER_PetCare.txt)

**Comment by bcaal87** [comment]
En la Wiki, pueden publicar el modelo de E/R

**Comment by arturosierra** [comment]
Gracias por la sugerencia ingeniero. 
Saludos.

**Comment by arturosierra** [comment]
Colega Jaime, me gustaria tuvieramos una sesion de discor hoy por la noche para que podamos debatir ciertos avances que tengo con la creacion de la BD, unicamente para estar de acuerdo y confirmar las tbl a utilizar.

**Comment by JaimeRax** [comment]
Con gusto, nos podemos conectar hoy a las 20:00 hrs. te mandare el enlace a tu correo

**Comment by JaimeRax** [comment]
Compañero @arturosierra  favor de publicar el modelo E/R en la wiki
