### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by JaimeRax** [PetCare-Veterinay/PetCare#2]
### UML

Creación de diagramas:

>  Diagrama de Casos de Uso
>  Diagrama de Clases
>  Diagrama de Secuencia
>  Diagrama de Actividad
>  Diagrama de Estado
>  Diagrama de Componentes
>  Diagrama de Despliegue
>  Diagrama de Paquetes

**Comment by madai120** [comment]
Hay alguna plataforma en especifico para trabajar los diagramas?

**Comment by EmelyTecu** [comment]
> ¿Hay alguna plataforma en especifico para trabajar los diagramas?

Podes tomar en cuenta StarUML

**Comment by madai120** [comment]
El diagrama de clases está listo

**Comment by madai120** [comment]
El diagrama de casos de uso está listo

**Comment by EmelyTecu** [comment]
Diagrama de secuencia  terminado

**Comment by madai120** [comment]
Los diagramas que debia trabajar estan terminados

**Comment by EmelyTecu** [comment]
Los diagramas ya están terminados
