### ISSUE TITLE
Create endpoint from service

### ISSUE THREAD

**Issue by JaimeRax** [PetCare-Veterinay/PetCare#4]
Necesitamos agregar un nuevo endpoint CRUD para administrar los servicios en nuestra aplicación. Este endpoint es esencial para realizar operaciones básicas de Crear, Leer, Actualizar y Eliminar registros de servicios.

**Comment by EmelyTecu** [comment]
Ya termine el endpoint CRUD para administrar los servicios

**Comment by EmelyTecu** [comment]
endpoint CRUD para administrar los tratamiento terminado

**Comment by EmelyTecu** [comment]
endpoint CRUD para administrar los pacientes terminado
