### ISSUE TITLE
Create views Diagnostico - Servicio

### ISSUE THREAD

**Issue by JaimeRax** [PetCare-Veterinay/PetCare#8]
Estamos buscando desarrollar una funcionalidad que permita la creación, edición y visualización de problemas de una manera más eficiente y amigable en nuestra plataforma. Para lograr esto, necesitamos la implementación de vistas de formularios personalizadas que se integren con los endpoints ya existentes en nuestro sistema.

**Comment by EmelyTecu** [comment]
Ya esta terminado todo
